load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "sim_device",
    srcs = ["lib.rs"],
    crate_root = "lib.rs",
    edition = "2024",
    visibility = ["//visibility:public"],
)

rust_library(
    name = "at_line",
    srcs = ["at_line.rs"],
    crate_root = "at_line.rs",
    edition = "2024",
    visibility = ["//device:__pkg__"],
)

rust_test(
    name = "at_line_test",
    crate = ":at_line",
    size = "small",
)
